from pathlib import Path
import json,csv
root=Path(__file__).resolve().parents[1]
models=[json.loads(p.read_text(encoding='utf-8')) for p in (root/'src/data/models').glob('*.json')]
doc=root/'docs';doc.mkdir(exist_ok=True)
def fact_schema(kind):
    return {'type':'object','additionalProperties':False,'required':['value','source','scope','note'],'properties':{'value':{'type':[kind,'null']},'source':{'type':['string','null']},'scope':{'enum':['installed','family','missing']},'note':{'type':'string','minLength':1}},'allOf':[{'if':{'properties':{'scope':{'const':'missing'}}},'then':{'properties':{'value':{'type':'null'},'source':{'type':'null'}}},'else':{'properties':{'value':{'type':kind},'source':{'type':'string','minLength':1}}}}]}
numbers=['ratedPowerMW','rotorDiameterM','hubHeightM','bladeCount','cutInMS','ratedWindMS','cutOutMS']
strings=['generator','powerControl','converter']
specs={**{k:fact_schema('number') for k in numbers},**{k:fact_schema('string') for k in strings},'gearbox':fact_schema('boolean')}
simkeys=list(models[0]['simulation'])
schema={'$schema':'http://json-schema.org/draft-07/schema#','$id':'urn:smartwind:turbine-schema','title':'Aerogenerador documental y simulación educativa','type':'object','additionalProperties':False,'required':list(models[0]),'properties':{'id':{'type':'string','pattern':'^[a-z0-9-]+$'},'manufacturer':{'type':'string'},'model':{'type':'string'},'supplier':fact_schema('string'),'parks':{'type':'array','minItems':1,'items':{'type':'object','additionalProperties':False,'required':['name','references','evidence','note','hubHeightM','installationProvider'],'properties':{'name':{'type':'string'},'references':{'type':'array','items':{'type':'string'}},'evidence':{'type':'string'},'note':{'type':'string'},'hubHeightM':fact_schema('number'),'installationProvider':{'type':['string','null']}}}},'specs':{'type':'object','additionalProperties':False,'required':list(specs),'properties':specs},'notes':{'type':'array','items':{'type':'string'}},'simulation':{'type':'object','additionalProperties':False,'required':simkeys,'properties':{**{k:{'type':'number','exclusiveMinimum':0} for k in simkeys if k!='assumptions'},'assumptions':{'type':'array','minItems':1,'items':{'type':'string'}}}},'asset':{'type':'object','additionalProperties':False,'required':['glb','lod','schematic'],'properties':{'glb':{'type':'string','pattern':'^models/[a-z0-9-]+\\.glb$'},'lod':{'type':'string','pattern':'^models/[a-z0-9-]+\\.glb$'},'schematic':{'type':'boolean'}}}}}
(root/'src/data/turbine.schema.json').write_text(json.dumps(schema,ensure_ascii=False,indent=2),encoding='utf-8')
labels={'ratedPowerMW':'P nominal (MW)','rotorDiameterM':'Rotor (m)','hubHeightM':'Buje instalado (m)','bladeCount':'Palas','generator':'Generador','gearbox':'Multiplicadora','powerControl':'Control','cutInMS':'Arranque (m/s)','ratedWindMS':'Nominal (m/s)','cutOutMS':'Corte (m/s)','converter':'Convertidor'}
def val(f):
    if f['value'] is None:return 'No documentado'
    v='Sí' if f['value'] is True else 'No' if f['value'] is False else str(f['value'])
    return v+(' [familia]' if f['scope']=='family' else ' [parque]')
lines=['# Modelos y proveedores del Biobío','','Fuente base: 02_PARQUES_COMPONENTES_BIOBIO.pdf, Smartwind v1.0, corte documental 03-10-2026. Corpus complementario: Goldwind 1,5 MW, Vestas 2 MW, Vestas 4 MW, Vestas V112 LCA 2011 y HTML local Nordex N149. Se conserva el nivel de evidencia del informe; las referencias Bxx son las de ese informe, no consultas nuevas.','','El catálogo registra nueve modelos o variantes y trece entradas de parque (Raki y Huajache separados). No es un censo actualizado ni una certificación por número de serie. Se usa el Biobío actual.','','## Fabricantes, suministro y parques','','| Fabricante / modelo | Potencia unitaria documentada | Parque(s) | Evidencia | Proveedor de instalación mencionado |','|---|---|---|---|---|']
for m in models:lines.append('| '+ ' | '.join([m['manufacturer']+' '+m['model'],val(m['specs']['ratedPowerMW']),', '.join(p['name'] for p in m['parks']),'; '.join(p['name']+': '+p['evidence']+' '+','.join(p['references']) for p in m['parks']),'; '.join(p['name']+': '+p['installationProvider'] for p in m['parks'] if p['installationProvider']) or 'No documentado'])+' |')
lines+=['','Fabricante, operador e instalador son roles distintos. «Proveedor» se entrega como fabricante identificado; el corpus no demuestra un contratista de suministro independiente para todos los parques. Tecnorenova/Greenwork/CJR son referencias de instalación, no fabricantes.','','## Datos técnicos extraídos','','Cada valor incluye su alcance. Ausencia de un dato no se reemplaza por la cifra de otra variante. Alturas de torre se conservan por parque.']
for title,keys in [('Geometría y arquitectura',['rotorDiameterM','hubHeightM','bladeCount','generator','gearbox','powerControl']),('Umbrales de operación y conversión',['cutInMS','ratedWindMS','cutOutMS','converter'])]:
    lines+=['','### '+title,'','| Modelo | '+' | '.join(labels[k] for k in keys)+' |','|'+'---|'*(len(keys)+1)]
    for m in models:lines.append('| '+m['model']+' | '+' | '.join(val(m['specs'][k]) for k in keys)+' |')
lines+=['','### Alturas y discrepancias','','San Matías: 140 m de torre reportados en el informe p. 5 [B13]. Se conserva en `parks[].hubHeightM` con la nota de confirmar la definición de altura de buje; no se transfiere a Campo Lindo. Las otras alturas instaladas no constan. Opciones de altura de familia V110: 75/80/95/110/120/125 m; Nordex hasta 164 m; V150 ofrece varias torres en el folleto. No se escoge una como instalada.','','V136 CP3.6 no hereda diámetro, pitch ni multiplicadora del V136-4.2. V112/E110/G114 no reciben diámetro por interpretación del nombre. El catálogo conserva los datos explícitos y hace visibles los vacíos.','','Las Peñas: constructor informa cuatro G114, 2 MW por unidad y 8,4 MW de proyecto; no se fija 2,1 MW ni 2,5 MW. Negrete: diez CP3.6 de 3,6 MW según CEN/operador frente a once de 3,45 MW según instalador; se conserva el alcance ensayado. San Matías: «N163 V150» se concilia con B13 como Vestas V150, manteniendo la inconsistencia. N149 de Los Olmos/Mesamavida: plataforma Delta4000 confirmada, modelo específico con evidencia de montaje. Alena: pedido y registro histórico, sin certificación de inventario 2026.','','Umbrales V150-4.2/4.5 del folleto comercial: 3 m/s de arranque, 24,5 m/s de corte. No se asignan a Mk3B/4,3 MW instaladas. V136-4.2: 3/25 m/s, no transferidos a CP3.6. Nordex: 20 m/s base y opción hasta 26 m/s, no certificada por parque. Goldwind: 22 m/s de corte en promedio de diez minutos, nominal estática 9,9 m/s.','','## Trazabilidad por campo','']
for m in models:
    lines+=['### '+m['manufacturer']+' '+m['model'],'']
    for k,f in m['specs'].items():lines.append('- '+labels[k]+': '+val(f)+'. '+(f['source'] or 'Sin fuente específica')+'. '+f['note'])
    lines+=['']+['- '+n for n in m['notes']]+['','Supuestos empleados en el escenario:','']+['- '+n for n in m['simulation']['assumptions']]+['']
(doc/'modelos-extraidos.md').write_text('\n'.join(lines),encoding='utf-8')
with (doc/'modelos-extraidos.csv').open('w',newline='',encoding='utf-8-sig') as file:
    writer=csv.writer(file);writer.writerow(['Fabricante','Modelo','Parques',*labels.values(),'Fuentes/alcance por campo'])
    for m in models:writer.writerow([m['manufacturer'],m['model'],', '.join(p['name'] for p in m['parks']),*[val(m['specs'][k]) for k in labels],json.dumps(m['specs'],ensure_ascii=False)])
print('Esquema JSON, tablas Markdown y CSV generados.')


